### ISSUE TITLE
Suggestion: More interactive mini map

### ISSUE THREAD

**Issue by Minhoquinha** [Detea/PekaED#33]
Making the mini map something you can draw in for example would be cool, even knowing not very useful(still, big areas could be drawned using it). In the case you are wondering how would you draw in the mini map, there could be a button at the top of the mini map's window written "draw" and another at the side of it written "view", so you could switch between those.
 Other thing that would be nice and can be merged with the zoom suggestion i made a couple minutes ago, is to be able to use the mouse scroll to make the white square in the mini map bigger or smaller, changing how zoomed in is the main screen.
 And the last idea for this is being able to see only background or only foreground in the mini map, now i don't if this could be used with the already existing button background/foreground or with another buttons like this same thing but at the bottom of the mini map's window, so you could have your mini map showing everything while the main screen only shows the background, or the mini map showing the background and the main screen showing the foreground, and so on.

**Comment by Detea** [comment]
Drawing on the mini map is possible, but would probably pretty anoying. The mini map represents each tile with one pixel and without zooming in the mini map, one pixel is pretty small.

I have experimented with flood fill, for filling big areas, but removed it because you could accidently
fill the whole map. This could maybe be fixed by having the biggest radius flood fill will allow be like 50 * 50 tiles. What do you think? Would flood fill be useful, even with this limitation?

The mini map will always show both layers, I'm not sure why you would want to see the foreground on the screen and the background on the mini map, could you elaborate?

**Comment by Minhoquinha** [comment]
In the case you could copy a big block of tiles in the main screen and paste it in the mini map, that would be nice.

The problem is that i have no idea if 50 * 50 is enough or too little...

It is because it would be nice if you can see all the map's background while making it, but if you are making the background it could be annoying to only be able to see the background in the mini map

**Comment by Detea** [comment]
This problem could also be solved by zooming the level panel out, I think that'd be a cleaner solution.

A map can be up to about 256 * 224 tiles, so 50 * 50 would'nt be tiny, but also not a lot. I have thought about it and an undo/redo feature would make filling the whole screen, by accident, less of a problem.

I'm still not sure about this feature. The visible parts of the background will be shown on the mini map and the parts that will be covered by the foreground will also be like that in the game. I don't see the benefits.

**Comment by Detea** [comment]
Issue closed, because zooming is gonna be implemented soon.
